# Generated by Django 4.2.6 on 2024-03-01 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shirt_is_bestseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('Category', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Brand', models.CharField(max_length=50)),
                ('Price', models.PositiveIntegerField()),
            ],
        ),
    ]
