# Generated by Django 4.2.6 on 2024-03-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_producct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producct',
            name='Image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
